version: '3.3'

networks:
  performance_testing:
    name: performance_testing

services:
  jmeter-runner:
    container_name: performance_testing_jmeter-runner
    image: vsds/jmeter-runner:latest
    networks:
      - performance_testing 
    volumes:
      - ./tests:/tmp/tests:rw
    ports:
      - 9009:80
    environment:
      - BASE_URL=http://localhost:9009
      - TEST_FOLDER_BASE=/tmp/tests
      # - SILENT=true
      # - MAX_RUNNING=1
      # - RUN_TEST_API_KEY=
      # - CHECK_TEST_API_KEY=
      # - DELETE_TEST_API_KEY=
