networks:
  performance_testing:
    name: performance_testing

services:
  jmeter-runner:
    container_name: performance_testing_jmeter-runner
    image: vsds/jmeter-runner:latest
    networks:
      - performance_testing 
    volumes:
      - ${TEST_FOLDER:-./tests}:/home/node/jmeter-runner/tests:rw
      - ${TEMP_FOLDER:-./temp}:/home/node/jmeter-runner/temp:rw
    ports:
      - 9000:80
    environment:
      - TEST_FOLDER_BASE=/home/node/jmeter-runner/tests
      - TEMP_FOLDER_BASE=/home/node/jmeter-runner/temp
      - SILENT=${SILENT:-false}
      - REFRESH_TIME=${REFRESH_TIME:-30}
      - RUN_TEST_API_KEY=${RUN_TEST_API_KEY:-}
      - CHECK_TEST_API_KEY=${CHECK_TEST_API_KEY:-}
      - DELETE_TEST_API_KEY=${DELETE_TEST_API_KEY:-}
      - CUSTOM_LABELS='threads size type component members_per_page'
