version: '3.3'

networks:
  performance_testing:
    name: performance_testing

services:
  jmeter-runner:
    container_name: performance_testing_jmeter-runner
    image: vsds/jmeter-runner:latest
    networks:
      - performance_testing 
    volumes:
      - ${TEST_FOLDER}:/home/node/jmeter-runner/tests:rw
    ports:
      - 9000:80
    environment:
      # - TEST_FOLDER_BASE=/home/node/jmeter-runner/tests
      - BASE_URL=${BASE_URL}
      - SILENT=${SILENT:-false}
      - MAX_RUNNING=${MAX_RUNNING:-1}
      - REFRESH_TIME=${REFRESH_TIME:-30}
      - RUN_TEST_API_KEY=${RUN_TEST_API_KEY:-}
      - CHECK_TEST_API_KEY=${CHECK_TEST_API_KEY:-}
      - DELETE_TEST_API_KEY=${DELETE_TEST_API_KEY:-}
